SRC_PATH = {{ package_name }}
MAKEFLAGS = --no-print-directory

# Dependency management
install:
	rye sync

quicksync:
	rye syc --no-lock

test:
	@rye run pytest --cov=$(SRC_PATH) $(SRC_PATH) --cov-report xml:.coverage.xml --cov-report lcov:.coverage.lcov

test-with-coverage: 
	@echo "––– Testing –––"
	@rye run diff-cover .coverage.xml
	@echo "✅✅✅ Tests passed ✅✅✅"

lint: ## Format code
	@echo "––– Linting –––"
	@rye run ruff format .
	@rye run ruff . --fix --unsafe-fixes \
		--extend-select F401 \
		--extend-select F841
	@echo "✅✅✅ Lint ✅✅✅"

types: ## Type-check code
	@echo "––– Type-checking –––"
	@rye run pyright $(SRC_PATH)
	@echo "✅✅✅ Types ✅✅✅"

validate_ci: ## Run all checks
	@echo "––– Running all checks –––"
	@make lint
	@make types
	## CI doesn't support local coverage report, so skipping full test
	@make test

docker_ci: ## Run all checks in docker
	@echo "––– Running all checks in docker –––"
	@docker rm -f {{ project_slug }} || true
	@docker build -t {{ project_slug }}:latest -f Dockerfile .
	@docker run {{ project_slug }} make validate_ci

pr: ## Submit a PR
	@rye run lm sync --squash --automerge