###########################
# Start template makefile #
###########################

SRC_PATH = {{ package_name }}
MAKEFLAGS = --no-print-directory

# Dependency management
install:
	rye sync --no-lock

quicksync:
	rye sync --no-lock

test:
	rye test

test-with-coverage: 
	@echo "––– Testing –––"
	@make test
	@rye run diff-cover .coverage.xml
	@echo "✅✅✅ Tests passed ✅✅✅"

lint: ## Format code
	@echo "––– Linting –––"
	@rye run ruff format .
	@rye run ruff . --fix --unsafe-fixes
	@echo "✅✅✅ Lint ✅✅✅"

# Like lint, but does not fail if there are errors
# Useful for e.g. pre-commit hooks
silent-lint:
	@echo "––– Formatting –––"
	@rye run ruff format --fix-only .
	@rye run ruff . --fix-only --unsafe-fixes
	@echo "✅✅✅ Format ✅✅✅"

types: ## Type-check code
	@echo "––– Type-checking –––"
	@rye run pyright .
	@echo "✅✅✅ Types ✅✅✅"

validate_ci: ## Run all checks
	@echo "––– Running all checks –––"
	@make lint
	@make types
	## CI doesn't support local coverage report, so skipping full test
	@make test

docker_ci: ## Run all checks in docker
	@echo "––– Running all checks in docker –––"
	docker build -t {{ project_slug }}_ci -f .github/Dockerfile.dev .
	docker run {{ project_slug }}_ci make validate_ci

#########################
# End template makefile #
#########################