SRC_PATH = {{ package_name }}
MAKEFLAGS = --no-print-directory

# Dependency management
install-dev:
	@pip install -e .[dev]

install:
	@make install-deps
	@make install-dev
	@pip install -e .

# Tasks
generate_coverage:
	@pytest --cov=$(SRC_PATH) $(SRC_PATH) --cov-report xml:.coverage.xml --cov-report lcov:.coverage.lcov

test: ## Run tests
	@echo "––– Testing –––"
	@make generate_coverage
	@diff-cover .coverage.xml --fail-under=80
	@echo "✅✅✅ Tests passed ✅✅✅"

format:
	@echo "––– Formatting –––"
	@ruff format . 
	@echo "✅✅✅ Formatting ✅✅✅"

lint: ## Format code
	@echo "––– Linting –––"
	@ruff . --fix \
		--extend-select F401 \
		--extend-select F841
	@echo "✅✅✅ Lint ✅✅✅"

types: ## Type-check code
	@echo "––– Type-checking –––"
	@pyright $(SRC_PATH)
	@echo "✅✅✅ Types ✅✅✅"

validate_ci: ## Run all checks
	@echo "––– Running all checks –––"
	@make lint
	@make types
## CI doesn't support local coverage report, so skipping full tests
	@make generate_coverage 
